### ISSUE TITLE
Reduce the number of lines of code in the accounts/models.py for the profile model

### ISSUE THREAD

**Issue by tech-priest-oscar** [21stPhenom/hexpremium#2]
`   def is_free_user(self):
        return self.plan == 'fr'

    def is_basic_user(self):
        return self.plan == 'bc'
    
    def is_pro_user(self):
        return self.plan == 'pr'

    def is_premium_user(self):
        return self.plan == 'pr'

####################### to something like #############################

    def is_plan(self, plan_name):
         return self.plan == plan_name
   

`

**Comment by 21stPhenom** [comment]
Fixed this too
