### ISSUE TITLE
Add related name for speed optimization

### ISSUE THREAD

**Issue by tech-priest-oscar** [21stPhenom/hexpremium#3]
` user = models.OneToOneField(User, on_delete=models.CASCADE, related_name = "profile")  
`

this way, you can access the related model like an attribute. Note that this works for only one-to-one
relationships, that's why I'm suggesting this in the Profile model. Also, according to my experience, 
it is performance-effective

`profile = user.profile`

**Comment by 21stPhenom** [comment]
Fixed.
